[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vent = "D84NnzkhujGzCjFCkShFH33XGMvNpCoQ2pcvEPHQApPM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kenjiebalona/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
